/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.Vista;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.Controlador.AlojamientosController;
import org.Controlador.HabitacionesController;
import org.Controlador.HibernateUtil;
import org.Controlador.ReservasController;
import org.model.Habitaciones;
import org.model.Usuario;
import org.model.Hoteles;

/**
 *
 * @author Mario González Gómez
 */
public class AlojamientoPg extends javax.swing.JPanel {

    /**
     * Creates new form Apartamentos
     */
    public AlojamientoPg() {
        initComponents();
        id.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        iconG = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        baños = new org.Vista.Paneles();
        jLabel1 = new javax.swing.JLabel();
        camas = new org.Vista.Paneles();
        jLabel3 = new javax.swing.JLabel();
        wifi = new org.Vista.Paneles();
        jLabel4 = new javax.swing.JLabel();
        precio = new org.Vista.Paneles();
        lblPre = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        desayuno = new org.Vista.Paneles();
        jLabel5 = new javax.swing.JLabel();
        titDes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextArea();
        id = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1040, 930));
        setPreferredSize(new java.awt.Dimension(1040, 930));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(1040, 930));
        jPanel13.setPreferredSize(new java.awt.Dimension(1040, 930));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("@nestify");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(509, 509, 509))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 1040, 50));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3256.png"))); // NOI18N
        jPanel13.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        iconG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1500H.png"))); // NOI18N
        jPanel13.add(iconG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2256.png"))); // NOI18N
        jPanel13.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6256.png"))); // NOI18N
        jPanel13.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5256.png"))); // NOI18N
        jPanel13.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        titulo.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        titulo.setText("jLabel5");
        jPanel13.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 540, 30));

        baños.setMinimumSize(new java.awt.Dimension(50, 50));
        baños.setPreferredSize(new java.awt.Dimension(50, 50));
        baños.setRoundBottomLeft(15);
        baños.setRoundBottomRight(15);
        baños.setRoundTopLeft(15);
        baños.setRoundTopRight(15);
        baños.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BaIco.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        baños.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        jPanel13.add(baños, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 100, 100));

        camas.setMinimumSize(new java.awt.Dimension(50, 50));
        camas.setRoundBottomLeft(15);
        camas.setRoundBottomRight(15);
        camas.setRoundTopLeft(15);
        camas.setRoundTopRight(15);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CamaIco.png"))); // NOI18N
        jLabel3.setText("jLabel1");

        javax.swing.GroupLayout camasLayout = new javax.swing.GroupLayout(camas);
        camas.setLayout(camasLayout);
        camasLayout.setHorizontalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(camasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        camasLayout.setVerticalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(camasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel13.add(camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 100, 100));

        wifi.setMinimumSize(new java.awt.Dimension(50, 50));
        wifi.setRoundBottomLeft(15);
        wifi.setRoundBottomRight(15);
        wifi.setRoundTopLeft(15);
        wifi.setRoundTopRight(15);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wifiIco.png"))); // NOI18N
        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout wifiLayout = new javax.swing.GroupLayout(wifi);
        wifi.setLayout(wifiLayout);
        wifiLayout.setHorizontalGroup(
            wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wifiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        wifiLayout.setVerticalGroup(
            wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(wifiLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel13.add(wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        precio.setMinimumSize(new java.awt.Dimension(50, 50));
        precio.setRoundBottomLeft(15);
        precio.setRoundBottomRight(15);
        precio.setRoundTopLeft(15);
        precio.setRoundTopRight(15);
        precio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPre.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPre.setText("jLabel1");
        lblPre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        precio.add(lblPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 28));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reservar ya");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        precio.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 120, 40));

        jPanel13.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 640, 220, 160));

        desayuno.setMinimumSize(new java.awt.Dimension(50, 50));
        desayuno.setRoundBottomLeft(15);
        desayuno.setRoundBottomRight(15);
        desayuno.setRoundTopLeft(15);
        desayuno.setRoundTopRight(15);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DesIco.png"))); // NOI18N
        jLabel5.setText("jLabel1");

        javax.swing.GroupLayout desayunoLayout = new javax.swing.GroupLayout(desayuno);
        desayuno.setLayout(desayunoLayout);
        desayunoLayout.setHorizontalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desayunoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        desayunoLayout.setVerticalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(desayunoLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel13.add(desayuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        titDes.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        titDes.setText("Descripción");
        jPanel13.add(titDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, -1, -1));

        jScrollPane1.setBorder(null);

        Desc.setEditable(false);
        Desc.setBackground(new java.awt.Color(255, 255, 255));
        Desc.setColumns(20);
        Desc.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Desc.setRows(5);
        Desc.setBorder(null);
        jScrollPane1.setViewportView(Desc);

        jPanel13.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 560, 100));
        jPanel13.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario u;
        Hoteles ht;
        Habitaciones h;
        ReservasController rc = new ReservasController();
        AlojamientosController ac = new AlojamientosController();
        HabitacionesController hc = new HabitacionesController();
        File f = new File("Logs.txt");
        BufferedReader br;
        try {
            int idHo = Integer.parseInt(id.getText());
            br = new BufferedReader(new FileReader(f));

            String email2 = br.readLine();

            HibernateUtil uc = new HibernateUtil();
            u = uc.obtenerUsuario(email2);
            ht = ac.obtenerAlojamientos(idHo);
            h = hc.filtrarHabitacion(ht);
            Date fechaEntrada = Date.valueOf(LocalDate.now());
            Date fechaSalida = Date.valueOf(LocalDate.now());

            rc.hacerReserva(u, h, ht, fechaEntrada, fechaSalida, h.getPrecio());
            br.close();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MiCuenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MiCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea Desc;
    private org.Vista.Paneles baños;
    private org.Vista.Paneles camas;
    private org.Vista.Paneles desayuno;
    public javax.swing.JLabel icon1;
    public javax.swing.JLabel icon2;
    public javax.swing.JLabel icon3;
    public javax.swing.JLabel icon4;
    public javax.swing.JLabel iconG;
    public javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblPre;
    private org.Vista.Paneles precio;
    public javax.swing.JLabel titDes;
    public javax.swing.JLabel titulo;
    private org.Vista.Paneles wifi;
    // End of variables declaration//GEN-END:variables
}
