/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.Vista;

/**
 *
 * @author Mario Clase
 */
public class AlojamientoPg extends javax.swing.JPanel {

    /**
     * Creates new form Apartamentos
     */
    public AlojamientoPg() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        icon1 = new javax.swing.JLabel();
        iconG = new javax.swing.JLabel();
        icon2 = new javax.swing.JLabel();
        icon3 = new javax.swing.JLabel();
        icon4 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        baños = new org.Vista.Paneles();
        camas = new org.Vista.Paneles();
        wifi = new org.Vista.Paneles();
        precio = new org.Vista.Paneles();
        lblPre = new javax.swing.JLabel();
        desayuno = new org.Vista.Paneles();
        titDes = new javax.swing.JLabel();
        Desc = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(1040, 930));
        setPreferredSize(new java.awt.Dimension(1040, 930));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setMinimumSize(new java.awt.Dimension(1040, 930));
        jPanel13.setPreferredSize(new java.awt.Dimension(1040, 930));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("@nestify");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(485, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(509, 509, 509))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(37, 37, 37))
        );

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 880, 1040, 50));

        icon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3256.png"))); // NOI18N
        jPanel13.add(icon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 0, -1, -1));

        iconG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1500H.png"))); // NOI18N
        jPanel13.add(iconG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        icon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2256.png"))); // NOI18N
        jPanel13.add(icon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, -1, -1));

        icon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6256.png"))); // NOI18N
        jPanel13.add(icon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, -1, -1));

        icon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5256.png"))); // NOI18N
        jPanel13.add(icon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, -1, -1));

        titulo.setText("jLabel5");
        jPanel13.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 480, 30));

        baños.setMinimumSize(new java.awt.Dimension(50, 50));
        baños.setPreferredSize(new java.awt.Dimension(50, 50));
        baños.setRoundBottomLeft(15);
        baños.setRoundBottomRight(15);
        baños.setRoundTopLeft(15);
        baños.setRoundTopRight(15);

        javax.swing.GroupLayout bañosLayout = new javax.swing.GroupLayout(baños);
        baños.setLayout(bañosLayout);
        bañosLayout.setHorizontalGroup(
            bañosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        bañosLayout.setVerticalGroup(
            bañosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel13.add(baños, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 100, 100));

        camas.setMinimumSize(new java.awt.Dimension(50, 50));
        camas.setRoundBottomLeft(15);
        camas.setRoundBottomRight(15);
        camas.setRoundTopLeft(15);
        camas.setRoundTopRight(15);

        javax.swing.GroupLayout camasLayout = new javax.swing.GroupLayout(camas);
        camas.setLayout(camasLayout);
        camasLayout.setHorizontalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        camasLayout.setVerticalGroup(
            camasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel13.add(camas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, 100, 100));

        wifi.setMinimumSize(new java.awt.Dimension(50, 50));
        wifi.setRoundBottomLeft(15);
        wifi.setRoundBottomRight(15);
        wifi.setRoundTopLeft(15);
        wifi.setRoundTopRight(15);

        javax.swing.GroupLayout wifiLayout = new javax.swing.GroupLayout(wifi);
        wifi.setLayout(wifiLayout);
        wifiLayout.setHorizontalGroup(
            wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        wifiLayout.setVerticalGroup(
            wifiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel13.add(wifi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        precio.setMinimumSize(new java.awt.Dimension(50, 50));
        precio.setRoundBottomLeft(15);
        precio.setRoundBottomRight(15);
        precio.setRoundTopLeft(15);
        precio.setRoundTopRight(15);
        precio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPre.setText("jLabel1");
        precio.add(lblPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 28, 65, 28));

        jPanel13.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 600, 220, 260));

        desayuno.setMinimumSize(new java.awt.Dimension(50, 50));
        desayuno.setRoundBottomLeft(15);
        desayuno.setRoundBottomRight(15);
        desayuno.setRoundTopLeft(15);
        desayuno.setRoundTopRight(15);

        javax.swing.GroupLayout desayunoLayout = new javax.swing.GroupLayout(desayuno);
        desayuno.setLayout(desayunoLayout);
        desayunoLayout.setHorizontalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        desayunoLayout.setVerticalGroup(
            desayunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel13.add(desayuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 600, -1, -1));

        titDes.setText("jLabel8");
        jPanel13.add(titDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 730, -1, -1));

        Desc.setText("jLabel9");
        jPanel13.add(Desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Desc;
    private org.Vista.Paneles baños;
    private org.Vista.Paneles camas;
    private org.Vista.Paneles desayuno;
    public javax.swing.JLabel icon1;
    public javax.swing.JLabel icon2;
    public javax.swing.JLabel icon3;
    public javax.swing.JLabel icon4;
    public javax.swing.JLabel iconG;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    public javax.swing.JLabel lblPre;
    private org.Vista.Paneles precio;
    public javax.swing.JLabel titDes;
    public javax.swing.JLabel titulo;
    private org.Vista.Paneles wifi;
    // End of variables declaration//GEN-END:variables
}
