/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.Vista;

import org.Controlador.HibernateUtil;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Mario González Gómez
 */
public class login extends javax.swing.JFrame {

   //SplashScreen cargar = new SplashScreen();
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
        //mostrarPanel(inicio);
        
        //cargar.mostrar();
        iniciar.putClientProperty( "FlatLaf.style", "arc: 15");  
        registrar.putClientProperty( "FlatLaf.style", "arc: 15");  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMov = new javax.swing.JPanel();
        iniciar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lbl1 = new javax.swing.JLabel();
        cerrar = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        icono = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(570, 360));
        setUndecorated(true);

        panelMov.setBackground(new java.awt.Color(255, 255, 255));
        panelMov.setPreferredSize(new java.awt.Dimension(570, 584));
        panelMov.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iniciar.setBackground(new java.awt.Color(154, 154, 154));
        iniciar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setText("Iniciar");
        iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarActionPerformed(evt);
            }
        });
        panelMov.add(iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 167, 48));

        registrar.setBackground(new java.awt.Color(154, 154, 154));
        registrar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        registrar.setForeground(new java.awt.Color(255, 255, 255));
        registrar.setText("Registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        panelMov.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 167, 48));
        panelMov.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 538, 10));

        lbl1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl1.setText("Iniciar sesión / Registrarse");
        panelMov.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblX.setText("X");
        cerrar.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        panelMov.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 26, -1));

        icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo3.png"))); // NOI18N
        panelMov.add(icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMov, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMov, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarActionPerformed
        IniciarS iniciar = new IniciarS();
        iniciar.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_iniciarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        Crear crear = new Crear();
        crear.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_registrarActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        lblX.setForeground(Color.black);
    }//GEN-LAST:event_cerrarMouseExited
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
           
            public void run() {
                new login().setVisible(true);
            }
        });
    }
    public void mostrarPanel(JPanel p){
        //definimos tamaño y posición del panel
        p.setSize(570, 584);
        p.setLocation(0,0);   

        //quitamos la ventana anterior y mostramos la nueva
        panelMov.removeAll();
        panelMov.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panelMov.revalidate();
        panelMov.repaint();
    }
    public void mostrarPanel2(JPanel p){
        //definimos tamaño y posición del panel
        p.setSize(570, 584);
        p.setLocation(0,0);   

        //quitamos la ventana anterior y mostramos la nueva
        panelMov.removeAll();
        panelMov.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        panelMov.revalidate();
        panelMov.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cerrar;
    private javax.swing.JLabel icono;
    private javax.swing.JButton iniciar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lblX;
    private javax.swing.JPanel panelMov;
    private javax.swing.JButton registrar;
    // End of variables declaration//GEN-END:variables
}
