/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.Vista;

import com.formdev.flatlaf.FlatLightLaf;
import org.Controlador.EmailUtil;
import org.Controlador.HibernateUtil;
import java.awt.Color;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.swing.JPanel;


/**
 *
 * @author Mario González Gómez
 */
public class RecuperarPass2 extends javax.swing.JPanel {

    /**
     * Creates new form Iniciar
     */
    public RecuperarPass2() {
        initComponents();
        FlatLightLaf.setup();
        continuar.putClientProperty( "FlatLaf.style", "arc: 15");
        pass.putClientProperty("FlatLaf.style", "arc: 15");
        pass.putClientProperty( "JTextField.placeholderText", "Contraseña");
        pass1.putClientProperty( "JTextField.placeholderText", "Contraseña");
        lblEm.setVisible(false);
        aviso.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPass = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();
        cerrar = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        lblEm = new javax.swing.JLabel();
        pass1 = new javax.swing.JPasswordField();
        lblPass1 = new javax.swing.JLabel();
        aviso = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(566, 361));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lbl1.setText("Recuperar contraseña");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 538, 10));

        lblPass.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblPass.setForeground(new java.awt.Color(153, 153, 153));
        lblPass.setText("Nueva contraseña");
        jPanel1.add(lblPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 120, -1));

        continuar.setBackground(new java.awt.Color(154, 154, 154));
        continuar.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        continuar.setForeground(new java.awt.Color(255, 255, 255));
        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        jPanel1.add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 144, 53));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        cerrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblX.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblX.setText("X");
        cerrar.add(lblX, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 26, 30));

        pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passMouseClicked(evt);
            }
        });
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 530, 60));
        jPanel1.add(lblEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        pass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pass1MouseClicked(evt);
            }
        });
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        jPanel1.add(pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 530, 60));

        lblPass1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(153, 153, 153));
        lblPass1.setText("Introduce de nuevo la nueva contraseña");
        jPanel1.add(lblPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 250, -1));

        aviso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        aviso.setForeground(new java.awt.Color(255, 0, 0));
        aviso.setText("LAS CONTRASEÑAS NO COINCIDEN.");
        jPanel1.add(aviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
            
            String emailText =lblEm.getText();
            
            if(pass.equals(pass1)){
                final String fromEmail="mariogongom4@gmail.com";
                final String password="wactidfkxukqdseq";
                final String toEmail=emailText;

                System.out.println("SSLMail Start");
                Properties props=new Properties();
                props.put("mail.smtp.host", "smtp.gmail.com");
                props.put("mail.smtp.starttls.enable", "true");
                props.put("mail.smtp.port", "587");
                props.put("mail.smtp.user", fromEmail);
                props.put("mail.smtp.auth", "true");
                props.put("mail.smtp.ssl.protocols","TLSv1.2");

                Authenticator auth = new Authenticator() {
                    protected PasswordAuthentication getPasswordAuthentication(){
                        return new PasswordAuthentication(fromEmail, password);
                    }
                };

                Session session = Session.getDefaultInstance(props, auth);
                System.out.println("Session created");
                EmailUtil.sendEmail(session, toEmail, "Cambio de contraseña", "Su contraseña ha sido cambiada. Si no la has cambiado tú, revisa tu cuenta.");

                HibernateUtil hu = new HibernateUtil();

                hu.actualizarUsuario(toEmail, password);

                IniciarS iniciar = new IniciarS();
                iniciar.setVisible(true);
                setVisible(false);
            }else{
                aviso.setVisible(true);
            }
            
    }//GEN-LAST:event_continuarActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        lblX.setForeground(Color.red);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        lblX.setForeground(Color.black);
    }//GEN-LAST:event_cerrarMouseExited

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        
    }//GEN-LAST:event_passActionPerformed

    private void passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passMouseClicked
        // TODO add your handling code here:
        pass.setText("");
    }//GEN-LAST:event_passMouseClicked

    private void pass1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pass1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1MouseClicked

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aviso;
    private javax.swing.JPanel cerrar;
    private javax.swing.JButton continuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl1;
    public javax.swing.JLabel lblEm;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblX;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass1;
    // End of variables declaration//GEN-END:variables
}
