package model;
// Generated 13 ene 2024, 20:22:33 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Habitaciones generated by hbm2java
 */
public class Habitaciones implements java.io.Serializable {

	private int numero;
	private int baños;
	private int camas;
	private int precio;
	private Set reservases = new HashSet(0);

	public Habitaciones() {
	}

	public Habitaciones(int numero, int baños, int camas, int precio, Set reservases) {
		this.numero = numero;
		this.baños = baños;
		this.camas = camas;
		this.precio = precio;
		this.reservases = reservases;
	}

	public int getNumero() {
		return this.numero;
	}

	public void setNumero(int numero) {
		this.numero = numero;
	}

	public int getBaños() {
		return this.baños;
	}

	public void setBaños(int baños) {
		this.baños = baños;
	}

	public int getCamas() {
		return this.camas;
	}

	public void setCamas(int camas) {
		this.camas = camas;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public Set getReservases() {
		return this.reservases;
	}

	public void setReservases(Set reservases) {
		this.reservases = reservases;
	}

}
