package model;
// Generated 13 ene 2024, 20:22:33 by Hibernate Tools 6.3.1.Final

/**
 * ReservasId generated by hbm2java
 */
public class ReservasId implements java.io.Serializable {

	private int habitacion;
	private int hotel;
	private int usuario;

	public ReservasId() {
	}

	public ReservasId(int habitacion, int hotel, int usuario) {
		this.habitacion = habitacion;
		this.hotel = hotel;
		this.usuario = usuario;
	}

	public int getHabitacion() {
		return this.habitacion;
	}

	public void setHabitacion(int habitacion) {
		this.habitacion = habitacion;
	}

	public int getHotel() {
		return this.hotel;
	}

	public void setHotel(int hotel) {
		this.hotel = hotel;
	}

	public int getUsuario() {
		return this.usuario;
	}

	public void setUsuario(int usuario) {
		this.usuario = usuario;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReservasId))
			return false;
		ReservasId castOther = (ReservasId) other;

		return (this.getHabitacion() == castOther.getHabitacion()) && (this.getHotel() == castOther.getHotel())
				&& (this.getUsuario() == castOther.getUsuario());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHabitacion();
		result = 37 * result + this.getHotel();
		result = 37 * result + this.getUsuario();
		return result;
	}

}
